import { useState } from "react";
import { ArrowRight, Check, CircleAlert, ExternalLink, Filter, LockKeyhole, MapPin, Plus, Shirt, WalletCards } from "lucide-react";
import AtlasShell from "@/components/AtlasShell";

const pageCopy = {
  inbox: { eyebrow: "Inbox · signal cards", title: "The next moves Atlas can prepare.", intro: "Each signal carries its evidence, implication, and a clear human decision point." },
  looks: { eyebrow: "Looks · outfit planner", title: "Compose from what you actually own.", intro: "Outfits use only confirmed garments. Atlas can rank and explain candidates, but never invents a piece." },
  wardrobe: { eyebrow: "Wardrobe · confirmed items", title: "Your wardrobe, with provenance.", intro: "Review captured garments, confirm what belongs, and keep outfit advice grounded in your actual closet." },
  money: { eyebrow: "Money review · deterministic findings", title: "See the recurring drain clearly.", intro: "Money review surfaces recurring charges and price changes for your approval. It never cancels anything." },
  sources: { eyebrow: "Sources · consent & health", title: "Choose what Atlas can access.", intro: "Every connector is explicit, read-only by default, and gated by consent." },
  tasks: { eyebrow: "Operations engine · task reminders", title: "Keep the open loops visible.", intro: "Task reminders turn evidence into a small, manageable next action without taking control away from you." },
  travel: { eyebrow: "Operations engine · travel timeline", title: "A calmer view of what is ahead.", intro: "Travel context is organized as a timeline so preparation can happen before the rush." },
} as const;

type PageKey = keyof typeof pageCopy;

function Header({ page }: { page: PageKey }) {
  const copy = pageCopy[page];
  return <div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#1e4ed8]">{copy.eyebrow}</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">{copy.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{copy.intro}</p></div>;
}

export function InboxPage() {
  const cards = [{ title: "Review your pending tasks", implication: "One item is overdue and three are due soon.", urgency: "urgent", action: "Review task list" }, { title: "Compare black running shoes", implication: "Five sources support the price range, but color still needs confirmation.", urgency: "review", action: "Open research" }];
  return <AtlasShell><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 lg:px-12 lg:py-10"><Header page="inbox" /><div className="mt-8 grid gap-6 xl:grid-cols-[1fr_320px]"><section className="space-y-4">{cards.map((card) => <article key={card.title} className="rounded-2xl border border-[#e3e8f0] bg-white p-5 shadow-sm"><div className="flex items-start gap-4"><span className={`mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full ${card.urgency === "urgent" ? "bg-[#f97362]" : "bg-[#e9a23b]"}`} /><div className="flex-1"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{card.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{card.implication}</p></div><span className="rounded-full bg-slate-50 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-slate-400">{card.urgency}</span></div><button className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#173a9b] px-3 py-2 text-xs font-semibold text-white">{card.action} <ArrowRight size={13} /></button><p className="mt-4 text-xs text-slate-400">Atlas can prepare · it will not act without you</p></div></div></article>)}</section><aside className="rounded-2xl border border-[#e3e8f0] bg-white p-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-400">What Atlas can access</p>{["Wardrobe · confirmed items", "Money review · deterministic findings", "Gmail · consent-gated read-only"].map((item) => <div key={item} className="mt-5 border-b border-[#edf0f5] pb-4 text-sm"><p className="font-medium">{item}</p><p className="mt-1 text-xs text-slate-400">No sends, buys, cancels, or mutations without approval.</p></div>)}</aside></div></div></AtlasShell>;
}

export function LooksPage() {
  const [vibe, setVibe] = useState("Minimalist coffee run");
  return <AtlasShell><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 lg:px-12 lg:py-10"><Header page="looks" /><div className="mt-7 flex flex-wrap gap-2">{["Minimalist coffee run", "Office day", "Date night", "Rainy errands"].map((item) => <button key={item} onClick={() => setVibe(item)} className={`rounded-full px-3 py-2 text-xs font-semibold ${vibe === item ? "bg-[#173a9b] text-white" : "border border-[#e3e8f0] bg-white text-slate-500"}`}>{item}</button>)}</div><section className="mt-6 rounded-2xl border border-[#e3e8f0] bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.16em] text-slate-400">Composed outfit</p><h3 className="mt-1 text-xl font-semibold">{vibe}</h3></div><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold uppercase text-emerald-700">confirmed only</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["top", "Oxford shirt", "white · warmth 1/3"], ["bottom", "Straight-leg trousers", "charcoal · warmth 2/3"], ["shoes", "Leather sneakers", "white · $4.20/wear"]].map(([role, name, meta]) => <div key={role} className="rounded-xl border border-[#edf0f5] bg-[#fbfcff] p-4"><Shirt className="text-[#1e4ed8]" size={18} /><p className="mt-5 text-[10px] font-bold uppercase tracking-wider text-slate-400">{role}</p><p className="mt-1 font-semibold">{name}</p><p className="mt-1 text-xs text-slate-400">{meta}</p></div>)}</div><p className="mt-5 text-xs text-slate-400">3 confirmed pieces · owned value of the look $245 · no visual try-on in this release</p></section></div></AtlasShell>;
}

export function WardrobePage() { return <AtlasShell><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 lg:px-12 lg:py-10"><Header page="wardrobe" /><div className="mt-8 flex items-center justify-between"><div className="flex gap-2"><button className="rounded-full bg-[#173a9b] px-3 py-2 text-xs font-semibold text-white">All items</button><button className="rounded-full border border-[#e3e8f0] bg-white px-3 py-2 text-xs font-semibold text-slate-500">Needs review</button></div><button className="inline-flex items-center gap-2 rounded-xl bg-[#173a9b] px-4 py-3 text-sm font-semibold text-white"><Plus size={16} /> Add a garment</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["Oxford shirt", "Straight-leg trousers", "Leather sneakers", "Rain shell"].map((item, index) => <article key={item} className="rounded-2xl border border-[#e3e8f0] bg-white p-4"><div className="flex h-32 items-center justify-center rounded-xl bg-[#eef3ff]"><Shirt className="text-[#5d8af0]" size={36} /></div><p className="mt-4 font-semibold">{item}</p><p className="mt-1 text-xs text-slate-400">{["top", "bottom", "shoes", "outerwear"][index]} · confirmed</p></article>)}</div></div></AtlasShell>; }

export function MoneyPage() { return <AtlasShell><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 lg:px-12 lg:py-10"><Header page="money" /><div className="mt-8 grid gap-5 md:grid-cols-3"><div className="rounded-2xl bg-[#173a9b] p-5 text-white"><WalletCards size={20} /><p className="mt-6 text-xs text-blue-100">Annualized recurring drain</p><p className="mt-1 text-3xl font-semibold">$684.00</p></div><div className="rounded-2xl border border-[#e3e8f0] bg-white p-5"><p className="text-sm text-slate-500">Findings</p><p className="mt-4 text-3xl font-semibold">02</p><p className="mt-1 text-xs text-slate-400">ready for review</p></div><div className="rounded-2xl border border-[#e3e8f0] bg-white p-5"><p className="text-sm text-slate-500">Mode</p><p className="mt-4 text-3xl font-semibold">Read-only</p><p className="mt-1 text-xs text-slate-400">no cancellation actions</p></div></div><section className="mt-6 rounded-2xl border border-[#e3e8f0] bg-white p-5"><div className="flex items-center gap-3"><CircleAlert className="text-[#f97362]" size={19} /><div><h3 className="font-semibold">SampleStream subscription renewal</h3><p className="mt-1 text-sm text-slate-500">Renews soon · annualized cost $240 · review before deciding</p></div></div><button className="mt-5 rounded-xl border border-[#e3e8f0] px-4 py-2.5 text-sm font-semibold text-slate-600">Open manual review guide</button></section></div></AtlasShell>; }

export function SourcesPage() { return <AtlasShell><div className="mx-auto max-w-5xl px-5 py-8 sm:px-8 lg:px-12 lg:py-10"><Header page="sources" /><div className="mt-8 rounded-2xl border border-blue-100 bg-blue-50 p-5 text-sm leading-6 text-slate-600"><LockKeyhole className="mb-3 text-[#1e4ed8]" size={19} /><p><strong>Consent boundary:</strong> connected sources are used only for the capability you approve. Gmail remains read-only and disconnected until its requested scope is present.</p></div><div className="mt-6 space-y-3">{[{ name: "Google Tasks", mode: "Connected · read-only", detail: "Task evidence is available to the priority queue." }, { name: "SerpApi", mode: "Connected · research", detail: "Shopping evidence is normalized with source trails." }, { name: "Cloudinary", mode: "Connected · private storage", detail: "Signed wardrobe image storage is configured." }, { name: "Telegram", mode: "Safe mode · delivery off", detail: "Health checks pass; no unsolicited messages are sent." }].map((source) => <div key={source.name} className="flex items-center gap-4 rounded-2xl border border-[#e3e8f0] bg-white p-5"><span className="h-2.5 w-2.5 rounded-full bg-emerald-400" /><div className="flex-1"><p className="font-semibold">{source.name}</p><p className="mt-1 text-xs text-slate-400">{source.detail}</p></div><span className="text-xs font-semibold text-slate-500">{source.mode}</span><ExternalLink className="text-slate-300" size={16} /></div>)}</div></div></AtlasShell>; }

export function TasksPage() { const [done, setDone] = useState(false); return <AtlasShell><div className="mx-auto max-w-4xl px-5 py-8 sm:px-8 lg:px-12 lg:py-10"><Header page="tasks" /><section className="mt-8 rounded-2xl border border-[#e3e8f0] bg-white p-5 shadow-sm"><div className="flex items-start gap-4"><div className="rounded-xl bg-[#eef3ff] p-3 text-[#1e4ed8]"><Check size={20} /></div><div className="flex-1"><p className={`font-semibold ${done ? "text-slate-400 line-through" : ""}`}>Review annual subscription renewal for SampleStream</p><p className="mt-2 text-sm text-slate-500">Due soon · sourced from Money review · Atlas will remind, not cancel.</p><button onClick={() => setDone(!done)} className="mt-5 rounded-xl bg-[#173a9b] px-4 py-2.5 text-sm font-semibold text-white">{done ? "Restore task" : "Mark complete"}</button></div><Filter className="text-slate-300" size={18} /></div></section></div></AtlasShell>; }

export function TravelPage() { return <AtlasShell><div className="mx-auto max-w-5xl px-5 py-8 sm:px-8 lg:px-12 lg:py-10"><Header page="travel" /><section className="mt-8 rounded-2xl border border-[#e3e8f0] bg-white p-5 shadow-sm"><div className="flex items-start gap-4"><div className="rounded-xl bg-[#eef3ff] p-3 text-[#1e4ed8]"><MapPin size={20} /></div><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-slate-400">Upcoming timeline</p><h3 className="mt-1 text-xl font-semibold">London work trip</h3><p className="mt-2 text-sm text-slate-500">Sample itinerary · preparation reminders appear here when travel evidence is connected.</p></div></div><div className="mt-6 border-l-2 border-blue-100 pl-5"><p className="text-xs font-semibold text-[#1e4ed8]">THU · 09:30</p><p className="mt-1 font-medium">Departure preparation</p><p className="mt-1 text-xs text-slate-400">Review weather, wardrobe, and open tasks before leaving.</p></div></section></div></AtlasShell>; }
