"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { AlertTriangle, TrendingDown, Shirt, RefreshCw, WalletCards } from "lucide-react";
import { formatMoney } from "@/lib/format";
import type { FindingRow, GarmentRow } from "@/lib/server/store";

interface StripState { annualizedTotal: number; currency: string; subscriptionCount: number; garmentCount: number; ownedValue: number; averageCPW: number | null; cpwGarmentCount: number; urgentFindings: Array<{ id: string; title: string; detail: string; href: string; urgency: "review" | "urgent" | "normal" }> }
function cpwValue(g: GarmentRow) { return g.price && g.wearCount > 0 ? g.price / g.wearCount : null; }

export function CommandStrip() {
  const [state, setState] = useState<StripState | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const [moneyRes, wardrobeRes] = await Promise.all([fetch("/api/money", { cache: "no-store" }), fetch("/api/wardrobe", { cache: "no-store" })]); const money = moneyRes.ok ? (await moneyRes.json() as { findings?: FindingRow[]; annualizedTotal?: number }) : {}; const wardrobe = wardrobeRes.ok ? (await wardrobeRes.json() as { garments?: GarmentRow[] }) : {}; const findings = money.findings ?? []; const confirmed = (wardrobe.garments ?? []).filter((g) => g.status === "confirmed"); const cpw = confirmed.map(cpwValue).filter((value): value is number => value !== null); const urgentFindings = findings.filter((f) => f.state === "active" && (f.trialEnd ?? f.nextRenewal)).slice(0, 3).map((f) => ({ id: f.id, title: `${f.merchant}${f.trialEnd ? " · trial ending" : " · renewing soon"}`, detail: f.trialEnd ? `Trial ends ${new Date(f.trialEnd).toLocaleDateString()}` : `Renews ${new Date(f.nextRenewal ?? "").toLocaleDateString()}`, href: "/money", urgency: f.trialEnd ? "urgent" as const : "review" as const })); setState({ annualizedTotal: Number(money.annualizedTotal ?? 0), currency: "USD", subscriptionCount: findings.filter((f) => f.state !== "ignored" && f.annualized !== null).length, garmentCount: confirmed.length, ownedValue: confirmed.reduce((sum, g) => sum + (g.price ?? 0), 0), averageCPW: cpw.length ? cpw.reduce((sum, value) => sum + value, 0) / cpw.length : null, cpwGarmentCount: cpw.length, urgentFindings }); } catch { setState(null); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <section className="grid animate-pulse grid-cols-1 gap-3 sm:grid-cols-3" aria-label="Loading overview">{[1, 2, 3].map((item) => <div key={item} className="h-36 rounded-3xl border border-[var(--color-line)] bg-[var(--color-surface)]" />)}</section>;
  if (!state) return <section className="rounded-3xl border border-amber-500/20 bg-amber-500/5 p-5 text-sm text-[var(--color-ink-muted)]">Overview metrics are unavailable right now. <button type="button" onClick={() => void load()} className="ml-1 font-semibold text-[var(--color-accent-deep)] underline">Retry</button></section>;
  const metrics = [{ label: "Annual commitments", value: formatMoney(state.annualizedTotal, state.currency), note: `${state.subscriptionCount} tracked finding${state.subscriptionCount === 1 ? "" : "s"}`, Icon: WalletCards, tone: "text-amber-600 bg-amber-500/10" }, { label: "Average cost per wear", value: state.averageCPW !== null ? formatMoney(state.averageCPW, "USD") : "—", note: state.cpwGarmentCount ? `${state.cpwGarmentCount} with wear data` : "Log wears to measure", Icon: Shirt, tone: "text-emerald-600 bg-emerald-500/10" }, { label: "Wardrobe value", value: formatMoney(state.ownedValue, "USD"), note: `${state.garmentCount} confirmed piece${state.garmentCount === 1 ? "" : "s"}`, Icon: TrendingDown, tone: "text-cyan-700 bg-cyan-500/10" }];
  return <section className="space-y-3" aria-label="Overview metrics"><div className="grid grid-cols-1 gap-3 sm:grid-cols-3">{metrics.map(({ label, value, note, Icon, tone }) => <article key={label} className="rounded-3xl border border-[var(--color-line)] bg-[color-mix(in_srgb,var(--color-surface)_84%,transparent)] p-5 shadow-[0_16px_40px_rgba(15,23,42,.05)] backdrop-blur-xl transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-center justify-between"><span className="text-[.68rem] font-semibold uppercase tracking-[.11em] text-[var(--color-ink-muted)]">{label}</span><span className={`grid size-8 place-items-center rounded-xl ${tone}`}><Icon size={15} /></span></div><p className="mt-5 font-display text-2xl font-semibold tracking-[-.04em] text-[var(--color-ink)]">{value}</p><p className="mt-1 text-xs text-[var(--color-ink-muted)]">{note}</p></article>)}</div>{state.urgentFindings.length > 0 && <div className="flex flex-wrap gap-2 rounded-2xl border border-amber-500/20 bg-amber-500/[.06] p-3">{state.urgentFindings.map((item) => <Link key={item.id} href={item.href} className="flex min-w-0 flex-1 items-center gap-2 rounded-xl px-2 py-1.5 text-xs no-underline transition hover:bg-white/60"><AlertTriangle size={14} className="shrink-0 text-amber-600" /><span className="truncate font-semibold text-[var(--color-ink)]">{item.title}</span><span className="hidden truncate text-[var(--color-ink-muted)] sm:block">{item.detail}</span></Link>)}</div>}<button type="button" onClick={() => void load()} className="inline-flex items-center gap-1.5 text-xs font-semibold text-[var(--color-ink-muted)] transition hover:text-[var(--color-accent-deep)]"><RefreshCw size={12} /> Refresh live data</button></section>;
}
