import Link from "next/link";
import { ArrowRight, Check, Eye, Lock, RefreshCw, Shirt, Sparkles, Wallet, Zap, type LucideIcon } from "lucide-react";
import { ThemeToggle } from "@/components/ThemeToggle";
import { RouteMark } from "@/components/RouteMark";
import { Reveal } from "@/components/Reveal";
import { AuthControls } from "@/components/AuthControls";
import { LandingPreviewCarousel } from "@/components/LandingPreviewCarousel";

const FEATURES = [
  { icon: Shirt, eyebrow: "Wardrobe", title: "Know what you own.", detail: "Capture your pieces, track cost-per-wear, and build looks from the wardrobe you actually confirmed.", tone: "blue" },
  { icon: Wallet, eyebrow: "Money", title: "Catch the quiet leaks.", detail: "Surface renewals, trials, and price changes before they become another forgotten charge.", tone: "amber" },
  { icon: Eye, eyebrow: "Evidence", title: "See why it matters.", detail: "Every signal arrives with context, source boundaries, and a clear next move—not a black-box score.", tone: "violet" },
  { icon: Lock, eyebrow: "Control", title: "You stay the operator.", detail: "Atlas prepares. You approve. Nothing is sent, bought, cancelled, or mutated without you.", tone: "green" },
];
const STEPS = [
  ["01", "Connect what matters", "Choose read-only sources and revoke them whenever you want."],
  ["02", "Atlas finds the signal", "Your real records become a calm queue of useful, explainable opportunities."],
  ["03", "You decide the move", "Approve, ignore, or keep the insight. Your control is the final step."],
];
const TRUST = [
  [Lock, "Read-only by default", "The model never authorizes itself."],
  [RefreshCw, "Portable by design", "Export your records whenever you need."],
  [Check, "Private by construction", "Account-scoped data and revocable connections."],
];
const SITE_NAV: Array<[string, string]> = [["#features", "Product"], ["#how-it-works", "How it works"], ["#pricing", "Pricing"], ["/settings/privacy", "Privacy"]];
const TRUST_ITEMS: Array<[LucideIcon, string, string]> = TRUST as Array<[LucideIcon, string, string]>;

export default function LandingPage() {
  return <div className="min-h-screen overflow-hidden bg-[var(--color-bg)] text-[var(--color-ink)]">
    <header className="sticky top-0 z-40 border-b border-[var(--color-line)] bg-[color-mix(in_srgb,var(--color-bg)_78%,transparent)] backdrop-blur-2xl">
      <div className="mx-auto flex h-[72px] w-[min(100%_-_32px,1180px)] items-center gap-4">
        <Link href="/" className="flex items-center gap-3 no-underline" aria-label="Atlas home"><RouteMark size={34} /><span><strong className="block font-display text-[1.08rem] tracking-[-.03em]">Atlas</strong><span className="hidden text-[.6rem] font-bold uppercase tracking-[.18em] text-[var(--color-ink-muted)] sm:block">Life, with clarity</span></span></Link>
        <nav className="hidden flex-1 items-center justify-center gap-1 md:flex" aria-label="Site navigation">
          {SITE_NAV.map(([href,label]) => href.startsWith('#') ? <a key={href} href={href} className="rounded-xl px-3 py-2 text-sm font-semibold text-[var(--color-ink-muted)] no-underline transition hover:bg-[var(--color-accent-soft)] hover:text-[var(--color-ink)]">{label}</a> : <Link key={href} href={href} className="rounded-xl px-3 py-2 text-sm font-semibold text-[var(--color-ink-muted)] no-underline transition hover:bg-[var(--color-accent-soft)] hover:text-[var(--color-ink)]">{label}</Link>)}
        </nav>
        <div className="ml-auto flex items-center gap-2"><AuthControls /><ThemeToggle /><Link href="/inbox" className="hidden items-center gap-2 rounded-xl bg-[var(--color-ink)] px-4 py-2.5 text-sm font-bold text-white no-underline shadow-lg transition hover:-translate-y-0.5 sm:inline-flex">Open Atlas <ArrowRight size={15} /></Link></div>
      </div>
    </header>

    <main id="main">
      <section className="relative isolate overflow-hidden bg-[var(--color-hero)] text-[var(--color-on-hero)]" aria-labelledby="hero-h">
        <div className="absolute -right-40 -top-40 size-[620px] rounded-full bg-cyan-300/20 blur-3xl" /><div className="absolute -bottom-60 left-1/4 size-[540px] rounded-full bg-violet-500/20 blur-3xl" />
        <div className="relative mx-auto grid w-[min(100%_-_32px,1180px)] items-center gap-14 px-0 py-20 sm:py-28 lg:grid-cols-[1.02fr_.98fr] lg:py-32">
          <div><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/[.08] px-3 py-1.5 text-[.68rem] font-bold uppercase tracking-[.16em] text-cyan-100"><Sparkles size={13} /> A calmer operating system for life admin</p><h1 id="hero-h" className="max-w-[11ch] font-display text-5xl font-semibold leading-[.98] tracking-[-.065em] sm:text-7xl">Your life, with a next move.</h1><p className="mt-7 max-w-[52ch] text-base leading-8 text-[var(--color-on-hero-muted)] sm:text-lg">Atlas brings your wardrobe, money, and everyday signals into one private surface—then asks before it acts.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/inbox" className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3.5 text-sm font-bold text-[var(--color-hero-deep)] no-underline shadow-xl transition hover:-translate-y-0.5">Start with Atlas <ArrowRight size={16} /></Link><a href="#how-it-works" className="inline-flex items-center gap-2 rounded-xl border border-white/20 bg-white/[.07] px-5 py-3.5 text-sm font-bold text-white no-underline backdrop-blur transition hover:bg-white/[.14]">See the loop</a></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs font-semibold text-white/55"><span className="inline-flex items-center gap-2"><Check size={14} className="text-emerald-300" /> Read-only first</span><span className="inline-flex items-center gap-2"><Check size={14} className="text-emerald-300" /> No surprise actions</span><span className="inline-flex items-center gap-2"><Check size={14} className="text-emerald-300" /> Export anytime</span></div></div>
          <div className="relative mx-auto w-full max-w-[500px]"><div className="absolute -inset-5 rounded-[36px] bg-gradient-to-br from-cyan-300/20 via-violet-300/10 to-transparent blur-2xl" /><div className="relative rounded-[30px] border border-white/15 bg-white/[.08] p-3 shadow-[0_30px_100px_rgba(0,0,0,.28)] backdrop-blur-2xl"><div className="overflow-hidden rounded-[22px] border border-white/10 bg-[#101a2c]/90 p-5 sm:p-7"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div className="flex items-center gap-2 text-sm font-bold"><span className="grid size-8 place-items-center rounded-xl bg-cyan-200/15 text-cyan-200"><Zap size={15} /></span> Atlas overview</div><span className="inline-flex items-center gap-2 rounded-full bg-emerald-300/10 px-2.5 py-1 text-[.62rem] font-bold uppercase tracking-[.12em] text-emerald-200"><span className="size-1.5 rounded-full bg-emerald-300" /> Ready</span></div><p className="mt-8 text-[.65rem] font-bold uppercase tracking-[.16em] text-cyan-200/65">Today’s useful signals</p><h2 className="mt-2 max-w-[10ch] font-display text-4xl font-semibold leading-[.98] tracking-[-.05em] text-white">Three things worth your attention.</h2><div className="mt-8 grid gap-3"><div className="rounded-2xl border border-white/10 bg-white/[.06] p-4"><div className="flex items-center justify-between"><span className="text-sm font-semibold text-white">Renewal in 4 days</span><span className="text-xs text-amber-200">Review</span></div><p className="mt-2 text-xs leading-relaxed text-white/45">A subscription is about to renew at a higher price.</p></div><div className="rounded-2xl border border-cyan-200/15 bg-cyan-200/[.07] p-4"><div className="flex items-center justify-between"><span className="text-sm font-semibold text-white">Your wardrobe is ready</span><span className="text-xs text-cyan-200">Prepare</span></div><p className="mt-2 text-xs leading-relaxed text-white/45">12 confirmed pieces. 3 low-wear opportunities.</p></div></div><div className="mt-5 flex items-center justify-between border-t border-white/10 pt-5 text-xs text-white/40"><span>Atlas prepares</span><span className="font-bold text-cyan-200">You approve →</span></div></div></div></div>
        </div>
      </section>

      <Reveal delay={.05}><LandingPreviewCarousel /></Reveal>

      <section className="mx-auto grid w-[min(100%_-_32px,1180px)] grid-cols-1 gap-3 py-10 sm:grid-cols-3"><div className="rounded-2xl border border-[var(--color-line)] bg-[var(--color-surface)] p-5"><p className="font-display text-3xl font-semibold tracking-[-.05em]">0</p><p className="mt-1 text-sm text-[var(--color-ink-muted)]">actions without approval</p></div><div className="rounded-2xl border border-[var(--color-line)] bg-[var(--color-surface)] p-5"><p className="font-display text-3xl font-semibold tracking-[-.05em]">2</p><p className="mt-1 text-sm text-[var(--color-ink-muted)]">life engines working together</p></div><div className="rounded-2xl border border-[var(--color-line)] bg-[var(--color-surface)] p-5"><p className="font-display text-3xl font-semibold tracking-[-.05em]">100%</p><p className="mt-1 text-sm text-[var(--color-ink-muted)]">read-only source access</p></div></section>

      <section id="features" className="mx-auto w-[min(100%_-_32px,1180px)] py-20 sm:py-28" aria-labelledby="features-h"><p className="eyebrow"><Sparkles size={14} /> What Atlas unlocks</p><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 id="features-h" className="max-w-[12ch] text-4xl font-semibold sm:text-5xl">Less life admin. More signal.</h2><p className="mt-4 max-w-[55ch] text-base leading-7 text-[var(--color-ink-muted)]">Atlas turns scattered details into a small number of useful decisions. That is the offer: a private command center that feels lighter than the work it removes.</p></div><Link href="/inbox" className="inline-flex w-fit items-center gap-2 text-sm font-bold text-[var(--color-accent-deep)] no-underline">Explore the app <ArrowRight size={15} /></Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2">{FEATURES.map(({icon:Icon,eyebrow,title,detail,tone}) => <article key={title} className={`group rounded-[26px] border border-[var(--color-line)] bg-[var(--color-surface)] p-6 shadow-[var(--shadow-card)] transition duration-300 hover:-translate-y-1 hover:shadow-[var(--shadow-pop)] sm:p-7`}><div className={`mb-8 grid size-11 place-items-center rounded-2xl ${tone==='blue'?'bg-blue-500/10 text-blue-600':tone==='amber'?'bg-amber-500/10 text-amber-600':tone==='violet'?'bg-violet-500/10 text-violet-600':'bg-emerald-500/10 text-emerald-600'}`}><Icon size={20} /></div><p className="text-[.66rem] font-bold uppercase tracking-[.16em] text-[var(--color-ink-muted)]">{eyebrow}</p><h3 className="mt-2 text-2xl font-semibold">{title}</h3><p className="mt-3 max-w-[38ch] text-sm leading-7 text-[var(--color-ink-muted)]">{detail}</p></article>)}</div></section>

      <section id="how-it-works" className="border-y border-[var(--color-line)] bg-[var(--color-surface)]" aria-labelledby="how-h"><div className="mx-auto w-[min(100%_-_32px,1180px)] py-20 sm:py-28"><p className="eyebrow"><RefreshCw size={14} /> The Atlas loop</p><h2 id="how-h" className="max-w-[13ch] text-4xl font-semibold sm:text-5xl">A better default for decisions.</h2><div className="mt-12 grid gap-4 lg:grid-cols-3">{STEPS.map(([n,t,d]) => <article key={n} className="relative rounded-[26px] border border-[var(--color-line)] bg-[var(--color-bg)] p-6 sm:p-8"><span className="font-display text-5xl font-semibold tracking-[-.08em] text-[var(--color-accent)]/35">{n}</span><h3 className="mt-7 text-xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-7 text-[var(--color-ink-muted)]">{d}</p></article>)}</div></div></section>

      <section id="pricing" className="mx-auto w-[min(100%_-_32px,1180px)] py-20 sm:py-28" aria-labelledby="pricing-h"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow justify-center"><Wallet size={14} /> Simple pricing</p><h2 id="pricing-h" className="text-4xl font-semibold sm:text-5xl">Start private. Grow when ready.</h2><p className="mt-4 text-base leading-7 text-[var(--color-ink-muted)]">Atlas is designed to prove value before it asks for commitment. The current product experience is available as a focused personal command center.</p></div><div className="mx-auto mt-10 max-w-[620px] rounded-[30px] border border-blue-300/35 bg-gradient-to-br from-blue-500/[.13] via-[var(--color-surface)] to-violet-500/[.12] p-1 shadow-[var(--shadow-pop)]"><div className="rounded-[26px] bg-[var(--color-surface-solid)] p-7 sm:p-9"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-[var(--color-accent-deep)]">Atlas Personal</p><h3 className="mt-3 font-display text-5xl font-semibold tracking-[-.06em]">Free<span className="ml-2 text-base font-medium tracking-normal text-[var(--color-ink-muted)]">while you build your rhythm</span></h3></div><span className="rounded-full bg-[var(--color-good-soft)] px-3 py-1.5 text-xs font-bold text-[var(--color-good-deep)]">No card required</span></div><ul className="mt-8 grid gap-3 text-sm text-[var(--color-ink-2)] sm:grid-cols-2">{['Wardrobe intelligence','Money signal review','Private account data','Export and delete controls','Approval-first recommendations','Responsive web app'].map(x => <li key={x} className="flex items-center gap-2"><Check size={16} className="text-[var(--color-good)]" /> {x}</li>)}</ul><Link href="/inbox" className="mt-8 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--color-ink)] px-5 py-3.5 text-sm font-bold text-white no-underline transition hover:-translate-y-0.5">Open Atlas <ArrowRight size={16} /></Link><p className="mt-4 text-center text-xs text-[var(--color-ink-muted)]">Pricing can evolve with your usage. Your data stays portable.</p></div></div></section>

      <section className="bg-[var(--color-hero)] text-[var(--color-on-hero)]"><div className="mx-auto grid w-[min(100%_-_32px,1180px)] gap-10 py-20 sm:py-24 lg:grid-cols-[1fr_.9fr] lg:items-end"><div><p className="eyebrow text-cyan-200"><Lock size={14} /> Trust boundary</p><h2 className="max-w-[12ch] text-4xl font-semibold sm:text-5xl">Useful enough to return to. Safe enough to trust.</h2><p className="mt-5 max-w-[52ch] leading-7 text-[var(--color-on-hero-muted)]">Atlas gives you context without taking control away. Read-only access, visible evidence, and a clear off switch are part of the product—not a footnote.</p></div><div className="grid gap-3">{TRUST_ITEMS.map(([Icon,title,detail]) => <div key={title} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/[.06] p-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-cyan-200/10 text-cyan-200"><Icon size={18} /></span><span><strong className="block text-sm">{title}</strong><span className="mt-1 block text-xs text-white/50">{detail}</span></span></div>)}</div></div></section>
    </main>

    <footer className="border-t border-[var(--color-line)] bg-[var(--color-surface)]"><div className="mx-auto flex w-[min(100%_-_32px,1180px)] flex-wrap items-center gap-5 py-7"><Link href="/" className="flex items-center gap-2.5 no-underline"><RouteMark size={24} /><strong>Atlas</strong></Link><nav className="flex flex-wrap gap-1 text-sm text-[var(--color-ink-muted)]" aria-label="Footer navigation"><a href="#features" className="rounded-lg px-2 py-1 no-underline hover:bg-[var(--color-accent-soft)]">Product</a><a href="#pricing" className="rounded-lg px-2 py-1 no-underline hover:bg-[var(--color-accent-soft)]">Pricing</a><Link href="/settings/privacy" className="rounded-lg px-2 py-1 no-underline hover:bg-[var(--color-accent-soft)]">Privacy</Link></nav><p className="m-0 text-xs text-[var(--color-ink-muted)] sm:ml-auto">Atlas prepares the next move. You decide.</p></div></footer>
  </div>;
}
